language: node_js

node_js:
- node

cache:
  yarn: true

addons:
  ssh_known_hosts: 35.190.169.212

env:
  - DEPLOY_HOST=35.190.169.212

script:
  - yarn run test
  - yarn run build

before_deploy:
- openssl aes-256-cbc -K $encrypted_d05dc4972430_key -iv $encrypted_d05dc4972430_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: /bin/bash scripts/deploy.sh $DEPLOY_HOST $TRAVIS_BUILD_DIR
  on:
    branch: master